site_name: Devansh Tripathi
site_url: https://devansh1106.github.io/
site_description: Academic website
site_author: Devansh Tripathi
copyright: Copyright &copy; 2024 Devansh Tripathi


theme:
  name: material
  icon: 
    logo: material/library
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    scheme: slate
    primary: purple
    accent: indigo
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    # - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking  
    - navigation.path
    - navigation.top
    - content.code.copy
    - posts.excerpts
    - standard.posts
  font:
    text: Sans Serif Mono
    code: Roboto Mono

plugins:
  - search
  - tags
  - blog:
      blog_dir: blog
  - blog:
      blog_dir: news
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - bibtex:
      bib_dir: "docs/bibfiles/"
      bib_by_default: false
  - ultralytics:
      add_desc: True
      add_image: True
      add_authors: True
      add_json_ld: True
      add_share_buttons: True
      # add_copy_llm: True
      default_image: https://avatars.githubusercontent.com/u/124599097?v=4
      default_author: devansh22@iisertvm.ac.in
  # - mkdocs-pdf
  # - awesome-pages

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - CV: index.md
  - News: 
    - news/index.md
  - Notes:
    - notes/index.md
  - Projects:
    - projects/index.md
  - Blog: 
    - blog/index.md

extra:
  favicon: docs/assets/icon_my_pic.ico
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Devansh1106
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Devansh_1106
    - icon: fontawesome/solid/envelope
      link: mailto:devansh22@iisertvm.ac.in

  analytics:
    provider: google
    property: G-DD6NHH0CZP